### ISSUE TITLE
Module generator - Step 3-Form display 

### ISSUE THREAD

**Issue by newbie15** [crocodic-studio/crudbooster#108]
untuk input mode select, option tidak muncul sama sekali, hanya tombol close dan save changes yang muncul.

kemudian ketika di klik ke next step, error

ErrorException in ModulsController.php line 381:
Invalid argument supplied for foreach()

**Comment by huthaifa-abd** [comment]
Hi , you can try the following solution it worked for me 
Edit the following file 
\vendor\crocodicstudio\crudbooster\src\controllers\ModulsController.php

On Line 381
Replace This
foreach($option[$i] as $key=>$val) {

With This
foreach((array)$option[$i] as $key=>$val) {

This changes fixed the foreach issue .
[ModulsController.txt](https://github.com/crocodic-studio/crudbooster/files/687960/ModulsController.txt)



Let me know if it helps , im not sure if this is a bug , but if it is i hope it gets fixed asap , since this is the best crud generator

Regards

**Comment by fherryfherry** [comment]
Bug fixed at master

**Comment by chayankiit** [comment]
![screenshot from 2017-11-14 11 29 13](https://user-images.githubusercontent.com/14080295/32765190-621436d0-c92f-11e7-92b9-32dd52578c2c.png)

Where code edit 

There are 

if(!CRUDBooster::isView() && $this->global_privilege==FALSE) {
			CRUDBooster::insertLog(trans('crudbooster.log_try_view',['module'=>$module->name]));
			CRUDBooster::redirect(CRUDBooster::adminPath(),trans('crudbooster.denied_access'));			
}

I can not find how to fix up.

**Comment by Devamit2016** [comment]
but is it good to change the vendor codes?i need solution without changing the vendor codes
