### ISSUE TITLE
how to print or xport the details page?

### ISSUE THREAD

**Issue by pablojnd** [crocodic-studio/crudbooster#1316]
how to export or ptint the details page as index

**Comment by perlbrain** [comment]
I'm looking at this also and thinking about https://github.com/barryvdh/laravel-dompdf.

**Comment by rascachu** [comment]
how to add a button and export with child form

![sin titulo](https://user-images.githubusercontent.com/25269490/49470983-6d1fab00-f7ea-11e8-92c7-a1836f1b2542.png)

**Comment by perlbrain** [comment]
You can use this to make to button in that spot (replace the "add"button with a print/pdf button:
https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-custom-view-add.md

Then you need to make (a custom) blade with a print method with:
https://github.com/barryvdh/laravel-dompdf
I'm still working on it to make it work.
Let me know if you're already done.

**Comment by perlbrain** [comment]
Did you see that https://github.com/barryvdh/laravel-dompdf is already included in the project

**Comment by perlbrain** [comment]
I'm sorry to say that I left this community because it just takes to long before the next version comes out.  I am not complaining because this is a free project and the makers probably are working on other projects. 

But I can tell that I used this:
https://appdividend.com/2017/05/08/generate-pdf-blade-laravel-5-4/

you can skip the first step, but you need to put the alias in.
in the step with the route you will need to replace this with the crudbooster.php file to make it work.

**Comment by marcq64** [comment]
Thanks a lot @perlbrain I appreciate ! Which dashboard | package are you using now ?

**Comment by perlbrain** [comment]
Hi Marc, I'm using Laravel Nova now, but it also has its problems. It's is paid and I got a discount (I think it's too expensive). Because it is paid you will receive updates and problems will be solved. And there are some free packages available that can really help with my project.

**Comment by marcq64** [comment]
Thanks, Good to know, since Curdbooster become a risk now: no support, no community, I'm loosing to much time. I will terminate  v1 of my project and implement another dashboard|package afterwards. Thanks again for your time and take care, cheers, Marc

**Comment by AlexEAA** [comment]
Sorry, very handy thing

**Comment by perlbrain** [comment]
I was trying out laravel nova, it is a paid solution. But, I was very disappointed.It has too many bugs and simple things which can be done in crudbooster, can't be done in nova.I have to say that I think crudbooster (free) is better than nova (paid.I also bought another CRUD solution by SXIMO from codecanyon, which is also very good in its core, but the guys who made this also sold a product which has too many bugs and support is dramatic. You can read it in the comments on codecanyon. I would say never to buy this solution because you will be very disappointed. I also tried other packages, but not really good or you need to program a lot more yourself in laravel.
I think that overall Crudbooster is the best solution, but it lacks in updates and people helping each other. I tried several other products and all have positive and negative sides and some of these really were a big disappointment for me. I hope that this Crudbooster community can lift itself up and it really can be a good solution for all of us. (because other solutions are really bad....)

    On Tuesday, March 12, 2019, 8:43:16 AM GMT+1, Marc Q <notifications@github.com> wrote:  
 
 
Thanks a lot @perlbrain I appreciate ! Which dashboard | package are you using now ?

**Comment by marcq64** [comment]
Hi @perlbrain, thanks for your feedback. 
Before turning to Crudbooster, I have tried Josh, Voyager and other Adminlte like packages. Like you I have made dispointing experiences. Crudbooster is certainly the best solution, but since the community and issuer are usually "unresponsive" and without support it's loose its value. Sad. I'm developing in other languages and the communities I have joined are naturally sharing and helping without thinking everyone should be omniscient.
I'm using now Crudbooster only for its "Adminlte" functionalities, privileges or roles, menu etc. and for simple CRUD, but not for more advanced forms like master and details forms etc for which I'm doing it the traditionel Laravel way. If I have an issue, I know I will always find an helping hand and support with follow-up in stackoverflow or Laracasts. And I will not have to wait for godot.
Good luck

**Comment by marcq64** [comment]
HOW TO :

For an action button to print data relative to an order (row) in a coupon :

**Action button :**

```
$this->addaction = array();
			$this->addaction[] = ['label'=>'Bon','url'=>('bon_de_livraison').'/[id]','color'=>'info','showIf'=>"[statusorderID] == 5"];
```

**Create | adapt your Model :**

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CouponDeliveryOrder extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'orders_detail';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];
}
```


```
**Create your custom function into your crudbooster Controller :**

	    public function delivery_coupon_pdf($id) {

			//dd($id);
			// Fetch all orderdata from database
			$orderdata['order'] = CouponDeliveryOrder::findOrFail($id);
			$datatopdf = PDF::loadView('pdf.delivery_coupon', $orderdata);
			// If you want to store the generated pdf to the server then you can use the store function
			# $pdf->save(storage_path().'_filename.pdf');
			// Finally, you can download the file using download function
			return $datatopdf->download('delivery_coupon.pdf');

		  }

```

**Create your blade :**

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Bon de livraison</title>
  <style type="text/css" ></style>
</head>

<body bgcolor="#F6E9DC" style="width:100%">
		<table style="width:100%">
			<h2>Bon de livraison</h2>
			<tr>
				<td>Laboratoire : {{ $order->laboratory }}</td>
			</tr>
			<tr>
				<td>Date de livraison : {{ date('d-m-Y', strtotime($order->deliverydate)) }}</td>
			</tr>
			<tr>
				<td>Client : </td>
			</tr>
			<tr>
				<td>Adresse : </td>
			</tr>
			<tr>
				<td>Tél. principal : </td>
			</tr>
			<tr>
				<td>Autre Tél. : </td>
			</tr>
			<tr>
				<td>Sub Total : {{ $order->subtotal }}</td>
			</tr>
			<tr>
				<td>A payer : {{ $order->productprice }}</td>
			</tr>
		</table>
</body>
</html>
```

**Comment by bhayron** [comment]
To print, edit the file

`\vendor\crocodic\crudbooster\src\views\default\form.blade.php:`

In line 15 put this

`<div>
            <button class="btn btn-primary" onclick="window.print()">Imprimir</button>
        </div>`
