### ISSUE TITLE
Change Date Language in 

### ISSUE THREAD

**Issue by tsegkos** [crocodic-studio/crudbooster#1371]
Do anyone have any clue how to change the language of the date on form details? Thank you in advance 
![image](https://user-images.githubusercontent.com/21200364/51319708-75fcd100-1a66-11e9-9069-121dc2170392.png)

**Comment by squidv3** [comment]
https://github.com/crocodic-studio/crudbooster/issues/822

**Comment by squidv3** [comment]
same problem. i try https://github.com/crocodic-studio/crudbooster/issues/1060 but work

**Comment by squidv3** [comment]
I was able to change it to my language.

1 - in the config / app.php folder - change the "locale" to your language. In my case pt_br
As far as I can see just by making this change it already changes to your language the datapicker.

In my case it did not change to why in the public / vendor / crudbooster / assets / adminlte / plugins / datepicker / locales folder it looked for the /bootstrap-datepicker.pt_br.js file because pt_br is my configured language in the config/app.php while in the local folder the language my language was pt-br so as the system did not think it was always in the default language en

**Comment by tsegkos** [comment]
I am not trying to change the language of the bootstrap-datepicker.js. I already did this. My issue is that I can't show the date on my language on the details page. For example I want to show "16 Ιανουαρίου 2019" instead of "16 January 2019".

**Comment by tsegkos** [comment]
Finally i found the solution here https://github.com/crocodic-studio/crudbooster/issues/822#issuecomment-423717244. Thank you.
