### ISSUE TITLE
set the admin path to /

### ISSUE THREAD

**Issue by wa7eedem** [crocodic-studio/crudbooster#154]
hi ,
I am trying to make the crud is my root app

setting the **ADMIN_PATH** in config to **empty** is always redirect to **/admin/login**

and setting it to  **/**   its will redirect to **http://login**

is there a way to make the Crud work directly in the main route /

also my laravel routes/web.php is empty .

thank you .

**Comment by fherryfherry** [comment]
unfortunately you this is a backend, actualy you can not set ADMIN_PATH to empty. If it set to empty, CB will use "admin" as a default path. 

If you wish to empty the ADMIN_PATH, you may try to : 
![image](https://cloud.githubusercontent.com/assets/6733315/23049964/0ece7510-f4f2-11e6-9da3-95dedc9f3a49.png)
Remove 
`?:'admin'`
so it to be : 
`$admin_path = config('crudbooster.ADMIN_PATH');`

But untested, DWYOR if there is an error / broken link.

**Comment by wa7eedem** [comment]
I never thought it's in the middleware :)
I change it and so far so good .

I know its a backend but I don't have any frontend pages right now and want to access it directly

thank you

**Comment by fherryfherry** [comment]
please note that if you update CB, your middleware will be replaced with newest

**Comment by wa7eedem** [comment]
yes , currently I'm using my fork , 
I Really wish if you consider removing the 'admin'
My application structure is :
- / = landing page
- /app =  the Frontend (laravel app)
- /admin = the Backend (another laravel app)
so it's not logical to the url to be admin/admin

thank you .

**Comment by fherryfherry** [comment]
we will consider about that in the future version

**Comment by renzocastillo** [comment]
Hi @wa7eedem  could you please tell me how did you solve it ? Because I've done what indicated here and everything its ok while accesing modules, but when I try to access a dashboard I get the following error:

![image](https://user-images.githubusercontent.com/21372177/57953985-40061700-78b7-11e9-9340-0c05299014aa.png)

At first it was showing default laravel welcome view but I deleted the route for it . Now I am getting 404. 

I've been searching for a solution at vendor/crocodicstudio/crudbooster/src/routes.php but not sure where to fix it.

**Comment by geoffsari** [comment]
Is good to handle this in the crudbooster's config file.

app\config\crudbooster.php
  ` 'ADMIN_PATH' => '/',`

**Comment by mdtanjilhasan** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/42772759/95040954-21483080-06f7-11eb-84ac-894e256da3b6.png)

I do not override the default methods, for getAdd, getEdit, getDelete and also details page but all links are always 404 not found
