### ISSUE TITLE
Update Profile

### ISSUE THREAD

**Issue by jdredondo** [crocodic-studio/crudbooster#164]
Updating the profile shows the following error

![image](https://cloud.githubusercontent.com/assets/22225860/23138403/4e63f2b0-f775-11e6-9810-03398f7c4ab8.png)

**Comment by furqon** [comment]
om Ferry,

(AdminCmsUsersController)
this problem occured because we include id_cms_privileges in form_inputan. (line: 34)
while below in line 48, this field is hidden. $this->hide_form      = ['id_cms_privileges'];

in CBController this field is unset, so the default value when its save (postEditSave) will be inputted as default = ''.

my solution right now, is remark this line:
$this->form[] = array("label"=>"Privilege","name"=>"id_cms_privileges","type"=>"select","datatable"=>"cms_privileges,name",'required'=>true);

but it would be problem as SuperAdmin, because he cannot edit privilege.
So, is it possible to unset also hidden field in postEditSave for $this->arr?

**Comment by fherryfherry** [comment]
5.3.1.7 just released, please update, don't forget to follow the update guide

**Comment by tomatoe45** [comment]
https://github.com/crocodic-studio/crudbooster/issues/168

**Comment by jdredondo** [comment]
It's Working (y)
