### ISSUE TITLE
Help, error on checkbox

### ISSUE THREAD

**Issue by pablo-dave** [crocodic-studio/crudbooster#201]
![agregar](https://cloud.githubusercontent.com/assets/24419145/23590668/4aba0d4c-01b2-11e7-91e0-b6796ca22080.png)

**Comment by fherryfherry** [comment]
Hi you did not set the dataenum in options button

**Comment by pablo-dave** [comment]
Ok thanks, yes but when I save it sends the same value always to the database, how do I configure it to send me true or false?

**Comment by recepogras** [comment]
This will do it:
`$this->form[] = ['label'=>'Ismain','name'=>'ismain','type'=>'checkbox','validation'=>'required|min:1|max:1','dataenum'=>'1|', 'width'=>'col-sm-10'];`

'dataenum'=>'1|'   This piece will usethe value 1 (true) and will not show any label since the label is already on the left side of the form.
