### ISSUE TITLE
Child, after update "columns" is missing .. thanks

### ISSUE THREAD

**Issue by pablo-dave** [crocodic-studio/crudbooster#232]
![child](https://cloud.githubusercontent.com/assets/24419145/23826809/d8c8a214-0672-11e7-9bd2-68695ec31399.png)

Where i can change columns attributes?

**Comment by marcosmaia** [comment]
The way and wait for an example, I created a FOREIGN KEY anyway it did not work # :/

**Comment by fherryfherry** [comment]
example is in progress

**Comment by marcosmaia** [comment]
@fherryfherry Please make a video showing how to create a child. Thanks!
I will be very grateful

**Comment by fherryfherry** [comment]
[form child](https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-to-make-a-child-form.md)

**Comment by yosie123** [comment]
Thanks for the tutorial, i was to manage to do that easily. 
If I look at the crudbooster demo site there is:
![screen1](https://cloud.githubusercontent.com/assets/23457607/24245560/b752fa1c-0fc3-11e7-8e91-753f8ad9ebf0.png)
Here you can see the '+Add Data' instead of the full form, like in your tutorial. How to get that?

In addition: Can I pull the full demo-site from crudbooster somewhere? (files + data)

**Comment by mthompson90** [comment]
I would also like to configure the child form the way it is on the demo site too!  

Thanks!- Mike
