### ISSUE TITLE
Form validation not working

### ISSUE THREAD

**Issue by lars-str** [crocodic-studio/crudbooster#285]
Hey guys,
today I installed crudBooster and I'm impressed how easy it is to create a new web application. After a while I realized that the validation is not working if some of my inputs are empty. They were just saved even if they were declared as required. I figured out that [line 725](https://github.com/crocodic-studio/crudbooster/blob/master/src/controllers/CBController.php#L725) in CBController.php is the reason for that conflict.

`if( !isset($request_all[$name]) ) continue;`

If the input is empty, the loop is skipped and the empty field was not included by the investigation of laravels validator. After I commented it out, everything works fine.

I'm wondering why not other people got that issue already before. Can anybody reproduce that phenomenon?

**Comment by fherryfherry** [comment]
what kind of require do you use? by using "required" key or in "validation" key? and also what kind of input type ? text ?

I don't face this issue. HTML5 Required Validation will be produced. So, if a user submits a form, it can't. Because HTML5 Required stopped it

![image](https://cloud.githubusercontent.com/assets/6733315/24386717/4b46abe4-139b-11e7-80bf-96329f517275.png)
