### ISSUE TITLE
structure of demos

### ISSUE THREAD

**Issue by franciscoluiz** [crocodic-studio/crudbooster#291]
why not?

currently:
http://crudbooster.com/demoo/

suggestion:
http://crudbooster.com/demo/crudboosterdemo
http://crudbooster.com/demo/simpleblog
http://crudbooster.com/demo/simplestockmanager

what do you think guys?

**Comment by fherryfherry** [comment]
The other one is not for preview, let the user downlod it self
Pada tanggal 29 Mar 2017 23.00, "Francisco" <notifications@github.com>
menulis:

**Comment by franciscoluiz** [comment]
but... why not open for demonstration?

**Comment by fherryfherry** [comment]
Nice idea, but not for at this time, make a project to become a demo,we
need to make sure all of the functions are blocked otherwise it can make a
dangerous issue for our server security. Because the people can sign in and
make any cruds

Btw have you try it all?
Pada tanggal 29 Mar 2017 23.15, "Francisco" <notifications@github.com>
menulis:
