### ISSUE TITLE
TokenMismatchError on /admin/login page

### ISSUE THREAD

**Issue by connormcwood** [crocodic-studio/crudbooster#313]
Changed the background of the login page and now I am unable to log in as it says the tokens do not match.

Magically fixed itself after I was syncing folder to a previous github build.

**Comment by tomatoe45** [comment]
@connormcwood hi.. in case you encounter that message again.. please run

> php artisan cache:clear

it is a basic laravel command for token.. 

Thanks.

**Comment by lsmoro** [comment]
Guys, just had the same problem, but the very strange thing is while the user called me to report the error (she's in another city), suddenly the error magically fixed and she got connect with my Super Admin user!! And I got connect with hers! We did nothing. What happened? I cannot allow that it happens again. Thoughts?

**Comment by fherryfherry** [comment]
Actually, there are many factors, and that comes from laravel
1. Users too long stay in the form and do not log in after some times. And cause the laravel session expired.
(in this case, you can try to change the limit time of session at config/session.php)
2. You did not change the default laravel session name, why it can be an issue?, let say you have 2 projects with CRUDBooster or laravel with the same domain. So at both project, your session would be same. If one of them has expired, it causes session in other your project also expired.
(In this case, you can try to change laravel_session name in every you create a new project, at config/session.php)
3. maybe there is any other...

**Comment by lsmoro** [comment]
Okay. 👍  I’ll check the 2 alternatives you said. 
Thank you so much, Ferry!

Lorena Moro

**Comment by lsmoro** [comment]
Hi @fherryfherry How are you? I've checked the two alternatives you said and the issue persists. I don't have another project running in the same domain and already reduced the limit time to 15 minutes. Do you recommend something more? Today a real mess happened, suddenly one of the supervisor session was opened in one of the sales operator session, and the sales operator session opened in my computer and my Super Admin session opened in the supervisor computer. It shuffled everything in the same time, crazy.
I'm pretty concerned because we're about to start a new project to another client and their project is more complex and has financial information involved, which is strictly confidential. I cannot allow that something like this happen with them, and take a risk suddenly one customer got logged in the account of another customer. Facing this, do you know some solution for this authentication issue? If you reply telling me this is a Laravel issue, probably I'll give up Laravel/CrudBooster and choose another framework. It's a shame, because I loved CrudBooster. Let me know your thoughts. Thanks, Lorena.

**Comment by stevensherah** [comment]
Can you work on your project its has so many issues please we love this product so much.
And it really takes a lot of time trying to figure out all these issues how we can fix them.
