### ISSUE TITLE
How To Using menu Helper on CRUD ???

### ISSUE THREAD

**Issue by AdnanSyarief** [crocodic-studio/crudbooster#335]
i want to use Helper to get automatic data from table such as profile 

![image](https://cloud.githubusercontent.com/assets/24912478/24873098/e0249830-1e49-11e7-9070-a36a9e8f63a7.png)

this is the field that automatic filled from database data_mahasiswa

![image](https://cloud.githubusercontent.com/assets/24912478/24873179/25796474-1e4a-11e7-9eab-d05ff148b8e5.png)

i read on documentation that use CRUDBooster::myId().

How i can use this script to my controller.

![image](https://cloud.githubusercontent.com/assets/24912478/24873292/7917d728-1e4a-11e7-97d6-94d4372f6a8e.png)

**Comment by jdredondo** [comment]
you can use
$this->form[] = array("label"=>"Nombre","name"=>"name",'required'=>true,**'value'=>CRUDBooster::myName()**,'validation'=>'required|alpha_spaces|min:3');
for form scaffolding

**Comment by AdnanSyarief** [comment]
thank you, it work for get the name, but i try to get another field different table. i try to get "NIM" that data is number, example "20130120095".  
i use CRUDBooster::myName() but it get the name not the field "NIM"

**Comment by jdredondo** [comment]
Replace CRUDBooster::myName() by DB::table('table_name')->first()->nim

El 10 abr. 2017 5:18 PM, "AdnanSyarief" <notifications@github.com> escribió:

thank you, it work for get the name, but i try to get another field
different table. i try to get "NIM" that data is number, example
"20130120095".
i use CRUDBooster::myName() but it get the name not the field "NIM"

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/crocodic-studio/crudbooster/issues/335#issuecomment-293095412>,
or mute the thread

**Comment by AdnanSyarief** [comment]
it work.... thank you...
