### ISSUE TITLE
How to build a filler manager? 

### ISSUE THREAD

**Issue by technoartista** [crocodic-studio/crudbooster#377]
I want to build a file manager that has all the uploaded photos and documents only for admin to view, add and delete.

**Comment by fherryfherry** [comment]
Sorry ?

**Comment by technoartista** [comment]
i want to manage the uploads like this http://laraadmin.com/docs/1.0/uploads_manager ..

**Comment by fherryfherry** [comment]
So you ask how to build a file manager like laraadmin?
I think you should build it your self, because unfortunately, CRUDBooster doesn't have it.

I just can give you a basic of the CRUDBooster structure knowledge

1. CRUDBooster images will be saved at storage/app/*,
2. You need to give a condition to the crudbooster upload function, whether it should use file manager or html upload standard. (CBController.php)
3. You need to create a seeder to record your new file manager feature so it can show the sidebar menu
(src/database/seeds), you can see the other sample of module how it works
4. Of course, you need to create a file manager controller (src/controllers)
5. Lastly, if you have done your new feature, you could push it to Github if you like.
