### ISSUE TITLE
Hi, I updated the my dashboard with latest version. I had users in the previous version now it show the users in the table view correctly but when I want to edit the user info the image doesn't appear in edit form,  please help me this is urgent

### ISSUE THREAD

**Issue by mommand** [crocodic-studio/crudbooster#42]
![screen shot 2016-09-24 at 10 16 57 am](https://cloud.githubusercontent.com/assets/4653953/18806404/a3e0673c-8240-11e6-906d-0b76557d6104.png)

**Comment by fherryfherry** [comment]
Hi for urgent purpose, you can edit UsersController in /vendor/crocoicstudio/crudbooster/src/controllers/UsersController.php , make sure the type of col upload, set to "upload", not "upload_standard"

Because in the newest version, the UsersController for photo, the type is set to "upload" it means Upload Gallery, if set to "upload_standard" it mean HTML upload mode. "upload_standard" and "upload" types is different file location , so the error message will be shown

while waiting the next update version..

**Comment by mommand** [comment]
Done, thanks from your support.
