### ISSUE TITLE
Use Bower or NPM to dependencies

### ISSUE THREAD

**Issue by AndresOchoaS** [crocodic-studio/crudbooster#444]
Hello everyone,

I see that you uses copies of any dependencie in folder `assets`. Why? Is it not possible to use dependency managers? Thanks!

**Comment by davodavodavo3** [comment]
@AndresOchoaS you are right its possible , but 
1.@AndresOchoaS have installed Node js and dependency managers, but John Doe cant install all that in his server because hi is novice in all that stuff.
2. Why when you install Laravel , they doesnt include  dependency manager for bootstrap?)))))))
I think this is dev's option.And inlcuding assets for now is more confortable for all users i think(NOVICE users)
In the future assets will be optimized

**Comment by AndresOchoaS** [comment]
Laravel comes with Laravel-Mix, this necessarily requires having installed NodeJS and NPM/Yarn.

The level of learning should not be an obstacle to improvements.

**Comment by davodavodavo3** [comment]
Yes i comes ,but they dont require dev. to use it, or make moves to create a new project.
Yes you are right,learning is gold.
But we should not train them, right?

**Comment by davodavodavo3** [comment]
Аnyway assets will be optimized in the future, for now there is othere issues and improvements that need to be added(fixed)
