### ISSUE TITLE
A non superadmin user, can create a superadmin user

### ISSUE THREAD

**Issue by vinnyparker** [crocodic-studio/crudbooster#461]
Hi. I'm running final testes on my crudbooster app. So i created an privilege that can create almost everything. but it is not a superadmin. And then I create another superadmin user with this user that is not a superadmin. I think this user can not see or edit or create a superadmin user.
how can I fix this?

**Comment by faustol** [comment]
In the module for user administration, the privilege attribute applies the filter so that the superadmin role does not appear
![paso1](https://cloud.githubusercontent.com/assets/7764339/25785349/b81e572c-3343-11e7-887a-b91a3b7ee584.png)
![paso2](https://cloud.githubusercontent.com/assets/7764339/25785350/bbd290a4-3343-11e7-9197-4f40fe810bd5.png)
![paso3](https://cloud.githubusercontent.com/assets/7764339/25785351/bd88439e-3343-11e7-985c-15588f5c18be.png)

That is all. You could add a new module that is what I have done in my case

**Comment by vinnyparker** [comment]
thanx. I'll try  this.
