### ISSUE TITLE
DataModal column

### ISSUE THREAD

**Issue by kinden** [crocodic-studio/crudbooster#479]
datamodal column problem.

thanks for solving unique field, but after updating latest version my datamodal columns was change in below image

after updating latest version.

![modal](https://cloud.githubusercontent.com/assets/27999833/25698334/4ac16e72-30e0-11e7-8f1c-fa37810cbd4b.PNG)

![modal1](https://cloud.githubusercontent.com/assets/27999833/25698335/4b81ad4a-30e0-11e7-8678-8896906066a3.PNG)

before update
![b](https://cloud.githubusercontent.com/assets/27999833/25698362/5f658f66-30e0-11e7-8a52-b8f4a4eb225c.PNG)

![b1](https://cloud.githubusercontent.com/assets/27999833/25698369/63ba1b90-30e0-11e7-93e6-140977688522.PNG)

i want before update

**Comment by fherryfherry** [comment]
Have you run the following command : 
`php artisan crudbooster:update`
?

**Comment by kinden** [comment]
Now it work. Thanks Fherry

**Comment by kinden** [comment]
I have updated just now latest one, but still problem is there in column Header.

![ddq](https://cloud.githubusercontent.com/assets/27999833/25778709/464ede16-3328-11e7-866e-c1f2503bd7d3.png)

**Comment by tomatoe45** [comment]
hi @fherryfherry i have same problem with that modal it doesn't show the alias when trying to add with

 > $columns[]
with Child Form

but it works with

> $this->form[]..

**Comment by jdredondo** [comment]
I have same problem

> hi @fherryfherry i have same problem with that modal it doesn't show the alias when trying to add with

$columns[]
with Child Form
but it works with

$this->form[]..

**Comment by fherryfherry** [comment]
@jdredondo @tomatoe45 please read this doc https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/form-datamodal.md 
![image](https://cloud.githubusercontent.com/assets/6733315/25860648/656651fe-350c-11e7-9f62-e1da43a3b2f7.png)

**Comment by jdredondo** [comment]
My code
`$columns[] = ['label'=>'Actividades','name'=>'id_actividades','type'=>'datamodal','datamodal_table'=>'actividades','datamodal_columns'=>'actividad,duracion,id_tipologias','datamodal_columns_alias'=>'Actividad,Duración,Tipología','datamodal_select_to'=>'duracion:duracion','datamodal_where'=>'','required'=>true,'datamodal_size'=>'large'];
			$columns[] = ['label'=>'Duracion','name'=>'duracion','type'=>'text','required'=>true,'readonly'=>true];
			$columns[] = ['label'=>'Estado','name'=>'estado_actividad','type'=>'select','dataenum'=>['Pendiente','Resuelta'],'required'=>true,'value'=>'Pendiente','readonly'=>(CRUDBooster::getCurrentMethod() == 'getAdd')?true:false];
			$this->form[] = ['label'=>'Actividades','name'=>'ordenes_actividades','type'=>'child','columns'=>$columns,'table'=>'ordenes_actividades','foreign_key'=>'id_ordenes_trabajo','required'=>true];`

And this is the result!

![2017-05-09](https://cloud.githubusercontent.com/assets/22225860/25873401/03f56a50-34d4-11e7-82b1-b9ad19d7c12c.png)

**Comment by jdredondo** [comment]
the solution is:
in the file /vendor/crocodicstudio/crudbooster/src/views/default/type_components/child/component.blade.php
in the line 73.
change:
`var url_{{$name_column}} = "{{CRUDBooster::mainpath('modal-data')}}?table={{$col['datamodal_table']}}&columns=id,{{$col['datamodal_columns']}}&name_column={{$name_column}}&where={{urlencode($col['datamodal_where'])}}&select_to={{ urlencode($col['datamodal_select_to']) }}";`

by 
`var url_{{$name_column}} = "{{CRUDBooster::mainpath('modal-data')}}?table={{$col['datamodal_table']}}&columns=id,{{$col['datamodal_columns']}}&name_column={{$name_column}}&where={{urlencode($col['datamodal_where'])}}&select_to={{ urlencode($col['datamodal_select_to']) }}&columns_name_alias={{urlencode($col['datamodal_columns_alias'])}}";`

**Comment by tomatoe45** [comment]
hi there @fherryfherry .. before i ask question here i just make sure to read full docs. the time that i ask question is the time that there is something wrong with the program.. columns header in now working with mine.. thanks to you @fherryfherry  and @jdredondo . and now trying to check if there is conflict with other code.. thank you.. :) good master piece @fherryfherry  btw.

**Comment by Muhammadinaam** [comment]
jdredondo's code is working. @fherryfherry please also update in master branch.

**Comment by YosuaAndreasAditya** [comment]
hi there.. 
I'm using laravel 5.3 and crudbooster version 5.4.0.8

I try using data modal via Module Wizard and set datamodal_columns_alias_name = Name as screenshot below : 

![capture1](https://user-images.githubusercontent.com/10912795/30254412-b4b0af80-96c2-11e7-94f0-d366ecbbdbe5.PNG)

But the result isn't as expected, the column name is blank as screenshot below : 

![capture2](https://user-images.githubusercontent.com/10912795/30254459-5bcc8ba4-96c3-11e7-8ef2-de92bf76023d.png)

Code generated by the Module Wizard as below : 

$this->form[] = ['label'=>'Department','name'=>'department','type'=>'datamodal','validation'=>'required','width'=>'col-sm-8','datamodal_table'=>'department','datamodal_columns'=>'name','datamodal_size'=>'small','datamodal_module_path'=>'department','datamodal_columns_alias_name'=>'Name'];

Then I check the code in the file /vendor/crocodicstudio/crudbooster/src/views/default/type_components/child/component.blade.php on line 76 as below : 

var url_{{$name_column}} = "{{CRUDBooster::mainpath('modal-data')}}?table={{$col['datamodal_table']}}&columns=id,{{$col['datamodal_columns']}}&name_column={{$name_column}}&where={{urlencode($col['datamodal_where'])}}&select_to={{ urlencode($col['datamodal_select_to']) }}&columns_name_alias={{urlencode($col['datamodal_columns_alias'])}}";

I think there is mismatch between variabel name datamodal_columns_alias in component.blade.php  and the code datamodal_columns_alias_name generated by Module Wizard..

Because when i change datamodal_columns_alias_name to datamodal_columns_alias the result are okay as screenshot below : 

![capture4](https://user-images.githubusercontent.com/10912795/30254632-ec7e158a-96c5-11e7-8495-a7dc3ee3a3bf.PNG)

Also, i found variabel name : datamodal_columns_alias_name in \vendor\crocodicstudio\crudbooster\src\views\default\type_components\datamodal\info.json as screenshot below : 

![capture3](https://user-images.githubusercontent.com/10912795/30254664-22116210-96c6-11e7-8701-56807a1e3e0f.png)

Anyone knows which file in crudbooster that generate the mismatch variable name ( as explained above ) when using Module Wizard ?
